BBBB BBBBBBBBBBBBBBBBBB

BB BBBBBBBBBBBBBBB
    
BBBB
    XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBBBBB BBB BBBBBBBBBBBB XXXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBB BBBBBXX

        BB BBBBBBBBBBB BBB BBBBBBBBBBBBBBBB
            XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXBBBBBXX
                FFFFBB BBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXXXX
        BBBBB

        XXXX XXXXXXXXXXXXXXX XX
            BB BBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXBB BBBBBB XXXXXXBBBBBBB BBBBBBBBBB BBBBBXXFFFFXXXXXXXBBBBB
                BBBBBBBBBBBB BBBBB
                BB BBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXBB BBBBBB XXXXXXBBBBBBB BBBBBBBBBB BBBBBXXFFFFXXXXXXXBBBBB
            BBBB
                XXXX XXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBB XXXXXXBBBBBBB BBBBBBBBBB BBBBBXXFFFFXXXXXXXBBBBB
                    BBBBBBBBBBBB BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBB XXXXXXBBBBBBB BBBBBBBBBB BBBBBXXFFFFXXXXXXXBBBBB
                XXXXXX
          BBBBB

            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
    XXXXXX
BBBBB
